version: '3'

services:
  ark-admin-web:
    image: arklnk/ark-admin:web
    container_name: ark-admin-web
    volumes:
      - ./deploy/web:/etc/nginx/conf.d
    ports:
      - "80:80"
    restart: always

  ark-admin-nest:
    image: arklnk/ark-admin:nest
    container_name: ark-admin-nest
    volumes:
      - ./deploy/etc/.env.production:/app/.env.production
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ark_admin
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./deploy/sql/:/docker-entrypoint-initdb.d/
    privileged: true
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass 123456  --appendonly yes"
    privileged: true
    restart: always